- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'testAD'
    subscriptionId: '49d0d327-7fb4-4dcb-bd0e-62a47bf0bd29'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'temp'
    location: 'South India'
    templateLocation: 'Linked artifact'
    csmFile: 'deploy.json'
    csmParametersFile: 'parameters.json'
    deploymentMode: 'Incremental'
    deploymentName: 'dep1july'
    deploymentOutputs: 'storageEndpoint'
- task: ARM Outputs@5
  inputs:
    ConnectedServiceNameSelector: 'ConnectedServiceNameARM'
    ConnectedServiceNameARM: 'testAD'
    resourceGroupName: 'temp'
    outputNames: 'storageEndpoint'
    whenLastDeploymentIsFailed: 'fail'
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'testAD'
    ScriptType: 'InlineScript'
    Inline: |
      # You can write your azure powershell scripts inline here. 
      # You can also pass predefined and custom variables to this script using arguments
      
      $armOutputObj = $storageEndpoint | convertfrom-json
      echo $armOutputObj